//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_StudentInfo
    {
        public int Id { get; set; }
        public int Admin_No { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public int Form { get; set; }
        public string Class { get; set; }
    }
}
